steps:
  # Step 1: Set up the environment
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'activate-service-account', '--key-file=/workspace/your-service-account-key.json']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sks001/myapp-staging:latest', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sks001/myapp-staging:latest']

  # Step 4: Deploy the application to Google Kubernetes Engine
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/myapp-deployment', 'myapp=gcr.io/sks001/myapp-staging:latest']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-staging-cluster'

timeout: '1800s'  # Set timeout for 30 minutes

